accelerator: null
accumulate_grad_batches: 2
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: null
batch_size: 8
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
default_root_dir: null
deterministic: false
distributed_backend: null
enable_pl_optimizer: null
fast_dev_run: false
filetype: lmdb
flush_logs_every_n_steps: 100
gpus: 1
gradient_clip_val: 0
label_dir: null
learning_rate: 0.0005
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
max_epochs: 10
max_steps: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 8
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
stochastic_weight_avg: false
sync_batchnorm: false
terminate_on_nan: false
tpu_cores: null
track_grad_norm: -1
train_dataset: data/lmdbs/train
truncated_bptt_steps: null
val_check_interval: 1.0
val_dataset: data/lmdbs/val
weights_save_path: null
weights_summary: top
